name: Bump Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cocogitto/cocogitto-action@v4
        id: cog
        continue-on-error: true
        with:
          command: bump
          args: --auto

      - name: Push version tag
        if: steps.cog.outcome == 'success'
        run: git push --tags
